name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r python/requirements.txt
      - run: pip install sphinx
      - run: pip install sphinx-rtd-theme
      - run: cd python/ && pytest --cov=motifcluster tests/
      - run: cd python/ && pylint --rcfile=.pylintrc motifcluster
      - run: cd python/doc/ && make html
      - run: cd python/ && coverage-lcov
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: python/lcov.info

  R:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt -y install pandoc
      - run: sudo apt -y install r-base
      - run: sudo apt-get -y install ghostscript
      - run: cd R/ && Rscript -e 'install.packages(c("igraph", "LICORS", "Matrix", "RSpectra", "covr", "knitr", "mclust", "rmarkdown", "testthat", "devtools", "spam", "roxygen2", "lintr"), lib="~/")'
      - run: cd R/ && Rscript -e 'library(devtools); document();'
      - run: cd R/ && Rscript -e 'library(devtools); check()'
      - run: cd R/ && Rscript -e 'library(devtools); build_manual(path="doc")'
      - run: cd R/ && Rscript -e 'library(devtools); build_vignettes()'
      - run: cd R/ && Rscript -e 'lint_package(linters = with_defaults(object_name_linter=NULL,object_usage_linter=NULL,cyclocomp_linter=NULL))'
      - run: cd R/ && Rscript -e 'covr::coveralls()'
