name: CI

on:
  push:
    branches:
      - main
      - develop
    tags: '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r python/requirements.txt
      - run: pip install sphinx
      - run: pip install sphinx-rtd-theme
      - run: cd python/ && pytest --cov=motifcluster tests/
      - run: cd python/ && pylint --rcfile=.pylintrc motifcluster
      - run: cd python/doc/ && make html
      - run: cd python/ && coverage xml
      - uses: codecov/codecov-action@v3
        with:
          files: ./python/coverage.xml
          fail_ci_if_error: true
          verbose: true

  R:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: "R/"
          extra-packages: |
            devtools
      - run: sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >-
            pandoc
            libcurl4-openssl-dev
            texlive-latex-base
            texlive-latex-extra
            texlive-fonts-extra
            ghostscript
          version: 1.0
      - run: cd R/ && Rscript -e "library(devtools); document()"
      - run: cd R/ && Rscript -e "library(devtools); test()"
      - run: cd R/ && Rscript -e "library(lintr); lint_package(linters = with_defaults(object_name_linter=NULL,object_usage_linter=NULL,cyclocomp_linter=NULL))"
      - run: cd R/ && Rscript -e "library(covr); cov = package_coverage(); to_cobertura(cov)"
      - uses: codecov/codecov-action@v2
        with:
          files: ./R/cobertura.xml
          fail_ci_if_error: true
          verbose: true

  julia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
          arch: x64
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: cd julia/MotifCluster && julia --color=yes --depwarn=yes --inline=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: julia/MotifCluster/src
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
