name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r python/requirements.txt
      - run: pip install sphinx
      - run: pip install sphinx-rtd-theme
      - run: cd python/ && pytest --cov=motifcluster tests/
      - run: cd python/ && pylint --rcfile=.pylintrc motifcluster
      - run: cd python/doc/ && make html
      - run: cd python/ && coverage xml
      - uses: codecov/codecov-action@v2
        with:
          files: ./python/coverage.xml
          fail_ci_if_error: true
          verbose: true

  R:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt -y install libcurl4-openssl-dev
      - run: sudo apt -y install pandoc
      - run: sudo apt -y install texlive-latex-base texlive-latex-extra texlive-fonts-extra
      - run: sudo apt -y install r-base
      - run: sudo apt-get -y install ghostscript
      - run: mkdir R_packages/
      - run: Rscript -e 'install.packages(c("igraph", "LICORS", "Matrix", "RSpectra", "covr", "knitr", "mclust", "rmarkdown", "testthat", "devtools", "spam", "roxygen2", "lintr", "qpdf"), lib="./R_packages/")'
      - run: cd R/ && Rscript -e '.libPaths("../R_packages/"); library(devtools); document()'
      - run: cd R/ && Rscript -e '.libPaths("../R_packages/"); library(devtools); test()'
      - run: cd R/ && Rscript -e '.libPaths("../R_packages/"); library(lintr); lint_package(linters = with_defaults(object_name_linter=NULL,object_usage_linter=NULL,cyclocomp_linter=NULL))'
      - run: cd R/ && Rscript -e '.libPaths("../R_packages/"); library(covr); cov = package_coverage(); to_cobertura(cov)'
      - uses: codecov/codecov-action@v2
        with:
          files: ./R/cobertura.xml
          fail_ci_if_error: true
          verbose: true
